# Tuned for RandomForest probability behavior
NOISE_THRESHOLD = 0.30
SUSPICIOUS_THRESHOLD = 0.45
ATTACK_THRESHOLD = 0.50
HIGH_CONF_THRESHOLD = 0.70

MIN_HIGH_CONF_ATTACKS = 10
MIN_ATTACK_RATIO = 0.20
MIN_CONFIDENCE_MEAN = 0.55
